Fix client could not init glance client
Now the client can not initialise glance client,
give the warning msg like:
# murano environment-create test-env
Could not initialise glance client. Image creation will be unavailable.

Have two issue about this:
1. can not get the endpoint correctly, the get endpoint
are all murano's endpoint. This is due to when get the endpoint, if have
the endpoint, will return this endpoint directly.
2. Get the correctly endpoint, init the glance client, give the error:
TypeError: "__init__() got an unexpected keyword argument 'endpoint_type'"
This is due to 'endpoint_type' argument.

Change-Id: I87df369eecc9b79cb7173967729351f7e601edc0
Closes-bug: #1594731
(cherry picked from commit df7ecbc290ae61a56ff98413baa5b84625063911)