Replace print statment with print function
In PY3, print should used as a function instead of a statement.
This is PY27 compatible as well.

For example, instances of the first case were replaced by the
second case:

>>> print 'help'
  File "<stdin>", line 1
    print 'help'
               ^
SyntaxError: Missing parentheses in call to 'print'

>>> print('help')
help

Change-Id: I247aedf4a3090c2d75338389cf383adb090da231
Closes-bug: #1594741