Fix env-template-add-app command failed
When use env-template-add-app add app to env template, give the error:
AttributeError: 'list' object has no attribute 'items'

This patch Fix it, adds new capabilities to the client to allows passing
a list of env_templates instead of one.

Change-Id: Ie4f42cf97e5b8ae79f6c943809c7d8763afe0eec
Closes-bug: #1547576